apiVersion: v2
name: resource-generator
version: 0.1.0
description: A helm chart for mass generation of Kubernetes resources
dependencies:
  - name: resource-generator
    repository: oci://quay.io/iliasandbox/charts
    version: 0.1.0
    alias: generator
